name: Slack Markdown Converter
author: Jeff Fasulkey
description: 'Converts markdown to Slack''s mrkdwn'
inputs:
  text:
    description: Markdown text to convert
    required: true
  url:
    description: URL to link to
    required: false
outputs:
  text:
    description: Converted Slack mrkdwn text
runs:
  using: node20
  main: dist/index.js
branding:
  icon: heart
  color: red
