name: Slack Markdown Converter
author: Jeff Fasulkey
description: 'Converts markdown to Slack''s mrkdwn'
inputs:
  text:
    description: Markdown text to convert
    required: true
  url:
    description: URL to link to
    required: false
outputs:
  text:
    description: Converted Slack mrkdwn text
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      shell: bash
      run: npm install
      
    - name: Run script
      shell: bash
      run: node index.js
      env:
        INPUT_TEXT: ${{ inputs.text }}
        INPUT_URL: ${{ inputs.url }}
branding:
  icon: heart
  color: red
