name: CICD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Convert
        id: convert
        uses: ./
        with:
          text: |
            # Heading 1

            ## Heading 2

            [Link](http://example.com)

            * List Item 1
            * List Item 2

      - name: Verify
        shell: bash
        env:
          ACTUAL: ${{ steps.convert.outputs.text }}
          EXPECTED: '*Heading 1*\n\n*Heading 2*\n\n<http://example.com|Link>\n\n•   List Item 1\n•   List Item 2\n'
        run: |
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "Actual: '$ACTUAL'"
            echo "Expected: '$EXPECTED'"
            exit 1
          fi
